spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/orca_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://orca:orcapwd@127.0.0.1:27017/orca_db?authSource=admin
    redis:
      host: redis
      password: redispwd

pulsar:
  address: pulsar://127.0.0.1:6650

dubbo:
  registry:
    address: nacos://127.0.0.1:8848

living:
  minutes: 14400
  play-prefix: http
