server:
  port: 8003

spring:
  messages:
    basename: i18n/messages
  profiles:
    active: dev
    include: ${spring.profiles.active}
  application:
    name: live-sharing


# dubbo
dubbo:
  registry:
    address: nacos://nacos:8848
  application:
    logger: slf4j
    name: ${spring.application.name}
    qos-enable: off

# jwt
jwt:
  # 注意各端保持一致
  secret: [JWT SECRET]
  # 单位 days
  expiration-time: 1
  token-prefix: Bearer
  header-string: Authorization


# spring doc
springdoc:
  api-info:
    name: ${spring.application.name}
    version: 1.0.0
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    enabled: true
    groups:
      enabled: true
  packages-to-scan: ag.orca
  group-configs:
    - group: 普通接口
      paths-to-match:
        - /v3/**