spring:
  messages:
    basename: i18n/messages
  profiles:
    active: dev
    include: ${spring.profiles.active}
  application:
    name: live-task
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/orca_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&useTimezone=true&serverTimezone=GMT%2B8
    password: root
    username: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20
      idle-timeout: 30000
      leak-detection-threshold: 30000
      connection-timeout: 20000
      max-lifetime: 120000
  data:
    mongodb:
      uri: mongodb://orca:orcapwd@mongo:27017/orca_db?authSource=admin
      auto-index-creation: true
    redis:
      host: redis
      port: 6379
      password: redispwd
      timeout: 10000ms
      connect-timeout: 10000ms
      client-name: ${spring.application.name}
      lettuce:
        pool:
          enabled: false
          max-active: 10
          max-idle: 10
          min-idle: 0

pulsar:
  address: pulsar://pulsar:6650

mybatis:
  mapper-locations: classpath*:ag/orca/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    default-executor-type: simple
    default-fetch-size: 100
    default-statement-timeout: 30

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


elasticjob:
  reg-center:
    server-lists: zookeeper:2181
    namespace: orca
    base-sleep-time-milliseconds: 10000
    max-sleep-time-milliseconds: 30000
    max-retries: 3
    connection-timeout-milliseconds: 600000
    session-timeout-milliseconds: 600000
  jobs:
    RoomStaticsRecordJob:
      elasticJobClass: ag.orca.living.job.RoomStaticsRecordJob
      shardingTotalCount: 5
      jobErrorHandlerType: LOG
      cron: 0 0/1 * * * ?
      misfire: true
      failover: true
      overwrite: true
    VideoStreamTaskJob:
      elasticJobClass: ag.orca.living.job.VideoStreamTaskJob
      shardingTotalCount: 1
      jobErrorHandlerType: LOG
      cron: 0 0/1 * * * ?
      misfire: true
      failover: true
      overwrite: true
    ChannelStaticsRecordJob:
      elasticJobClass: ag.orca.living.job.ChannelStaticsRecordJob
      shardingTotalCount: 5
      jobErrorHandlerType: LOG
      cron: 0 0/1 * * * ?
      misfire: true
      failover: true
      overwrite: true
    TongLianPayQueryJob:
      elasticJobClass: ag.orca.living.job.TongLianPayQueryJob
      shardingTotalCount: 5
      jobErrorHandlerType: LOG
      cron: 0 0/1 * * * ?
      misfire: true
      failover: true
      overwrite: true
    ChangeCommissionRationsJob:
      elasticJobClass: ag.orca.living.job.ChangeCommissionRatiosJob
      shardingTotalCount: 1
      jobErrorHandlerType: LOG
      cron: 0 1,2,3 0 * * ?
      misfire: true
      failover: true
      overwrite: true
    OrgAccountStaticsRecordJob:
      elasticJobClass: ag.orca.living.job.OrgAccountStaticsRecordJob
      shardingTotalCount: 1
      jobErrorHandlerType: LOG
      cron: 0 0 1 * * ?
      misfire: true
      failover: true
      overwrite: true


