spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/orca_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://orca:orcapwd@127.0.0.1:27017/orca_db?authSource=admin
    redis:
      host: 127.0.0.1
      password: redispwd

pulsar:
  address: pulsar://127.0.0.1:6650

elasticjob:
  reg-center:
    server-lists: 127.0.0.1:2181