spring:
  datasource:
    url: jdbc:mysql://mysql:3306/orca_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://orca:orcapwd@mongo:27017/orca_db?authSource=admin
    redis:
      host: redis
      password: redispwd

pulsar:
  address: pulsar://pulsar:6650

elasticjob:
  reg-center:
    server-lists: zookeeper:2181
