dubbo:
  registry:
    address: nacos://127.0.0.1:8848

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/orca_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root
